package android.architecture.alok.com.androidarchitecture.analytics;

/**
 * A collection of Google Analytics trackers. Fetch the tracker you need using
 * {@code AnalyticsTrackers.getContext().get(...)}
 * <p/>
 * This code was generated by Android Studio but can be safely modified by
 * hand at this point.
 * <p/>
 * before using this!
 */
public final class AnalyticsTrackers {

    public enum Target {
        APP,
        // Add more trackers here if you need, and update the code in #get(Target) below
    }

    private static AnalyticsTrackers sInstance;

    public static synchronized AnalyticsTrackers getInstance() {
        if (sInstance == null) {
            sInstance = new AnalyticsTrackers();
        }
        return sInstance;
    }

    //private final Map<Target, Tracker> mTrackers = new HashMap<>();

    /**
     * Don't instantiate directly - use {@link #getInstance()} instead.
     */
    private AnalyticsTrackers() {
    }

    /*public synchronized Tracker get() {
        if (!mTrackers.containsKey(Target.APP)) {
            Tracker tracker = null;
            switch (Target.APP) {
                case APP:
                    tracker = GoogleAnalytics.getInstance(PBCareApplication.getContext()).newTracker(R.xml.app_tracker);
                    break;
                default:
                    //throw new IllegalArgumentException("Unhandled analytics target " + target);
            }
            mTrackers.put(Target.APP, tracker);
        }

        return mTrackers.get(Target.APP);
    }*/
}
